messages:
  afkautoset: "&7You are now afk"
  afkremoved: "&7You are no longer afk"
  playerafk: "&7%playername% is currently afk: %reason%"
  generalError: "&cAn error occurred while performing the command"
  notPlayer: "&cYou are not a player!"
  noPermission: "&cYou don't have required permissions to perform this action!"
  wrongUsage: "&cWrong usage!\nUsage: %usage%"
  afkset: "&7You have set your afk: %reason%"
  afklist: "&f%playername% is currently afk: %reason%"

settings:
  autoafk: true
  removeafkonmove: true
  removeafkonchat: true
  removeafkonattack: true
  removeafkoncommand: true
  removeafkoninteract: true
  removeafkonblockplace: true
  removeafkonblockbreak: true

options:
  afklength: 10